version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0 #use cimg or circleci
    steps:
      - checkout
  
  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout

  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
